from __future__ import annotations

"""
SanskritAI
==========

Lexical Resolution Result

Purpose
-------
Represents the canonical outcome of lexical resolution.

Unlike the legacy implementation, this class returns canonical
knowledge objects while preserving the ranked lookup
candidates generated by the LexicalLookupEngine.

Architecture
------------

ResolutionResult
        │
        ▼
LexicalResolutionResult
        │
        ├── LookupCandidate*
        │       │
        │       ├── CanonicalDictionaryEntry
        │       └── CanonicalDictionarySense
        │
        ├── CanonicalContext
        └── CanonicalSource

The result preserves ALL ranked candidates while exposing
convenience properties for the preferred (highest-ranked)
candidate.

Version
-------
v2.1.0
"""

from dataclasses import dataclass, field

from SanskritAI.domain.lexical.lookup_candidate import (
    LookupCandidate,
)

from SanskritAI.domain.resolution.resolution_result import (
    ResolutionResult,
)

from SanskritAI.acquisition.knowledge.models.canonical_context import (
    CanonicalContext,
)

from SanskritAI.acquisition.knowledge.models.canonical_dictionary_entry import (
    CanonicalDictionaryEntry,
)

from SanskritAI.acquisition.knowledge.models.canonical_dictionary_sense import (
    CanonicalDictionarySense,
)

from SanskritAI.acquisition.knowledge.models.canonical_source import (
    CanonicalSource,
)


@dataclass(
    frozen=True,
    slots=True,
)
class LexicalResolutionResult(
    ResolutionResult,
):
    """
    Immutable lexical resolution result.
    """

    candidates: tuple[
        LookupCandidate,
        ...
    ] = field(default_factory=tuple)

    matched_word_form: str = ""

    normalized_word_form: str = ""

    ambiguity_detected: bool = False

    # ---------------------------------------------------------
    # Candidate Information
    # ---------------------------------------------------------

    @property
    def has_candidates(
        self,
    ) -> bool:
        return bool(self.candidates)

    @property
    def candidate_count(
        self,
    ) -> int:
        return len(self.candidates)

    @property
    def preferred_candidate(
        self,
    ) -> LookupCandidate | None:

        if not self.candidates:
            return None

        return self.candidates[0]

    # ---------------------------------------------------------
    # Canonical Objects
    # ---------------------------------------------------------

    @property
    def preferred_entry(
        self,
    ) -> CanonicalDictionaryEntry | None:

        candidate = self.preferred_candidate

        if candidate is None:
            return None

        return candidate.entry

    @property
    def preferred_sense(
        self,
    ) -> CanonicalDictionarySense | None:

        candidate = self.preferred_candidate

        if candidate is None:
            return None

        return candidate.sense

    @property
    def has_entry(
        self,
    ) -> bool:
        return self.preferred_entry is not None

    @property
    def has_sense(
        self,
    ) -> bool:
        return self.preferred_sense is not None

    @property
    def canonical_context(
        self,
    ) -> CanonicalContext | None:

        sense = self.preferred_sense

        if sense is None:
            return None

        return sense.context

    @property
    def canonical_source(
        self,
    ) -> CanonicalSource | None:

        sense = self.preferred_sense

        if sense is None:
            return None

        return sense.source

    # ---------------------------------------------------------
    # Convenience
    # ---------------------------------------------------------

    @property
    def headword(
        self,
    ) -> str | None:

        entry = self.preferred_entry

        if entry is None:
            return None

        return entry.headword

    @property
    def lemma(
        self,
    ) -> str | None:
        """
        Return the preferred canonical entry lemma as text.

        CanonicalDictionaryEntry owns the lemma directly and
        exposes its textual representation through ``lemma_text``.

        A compatibility fallback is retained for legacy
        entry-like objects that expose ``lexeme.lemma``.
        """

        entry = self.preferred_entry

        if entry is None:
            return None

        lemma_text = getattr(
            entry,
            "lemma_text",
            None,
        )

        if lemma_text is not None:
            return str(lemma_text)

        lexeme = getattr(
            entry,
            "lexeme",
            None,
        )

        if lexeme is not None:
            lemma = getattr(
                lexeme,
                "lemma",
                None,
            )

            if lemma is not None:
                return str(lemma)

        lemma = getattr(
            entry,
            "lemma",
            None,
        )

        if lemma is not None:
            return str(lemma)

        return None

    @property
    def lexeme(
        self,
    ):
        """
        Return a legacy lexeme object when the preferred entry
        exposes one.

        CanonicalDictionaryEntry does not currently define a
        ``lexeme`` relationship, so canonical entries return None.
        """

        entry = self.preferred_entry

        if entry is None:
            return None

        return getattr(
            entry,
            "lexeme",
            None,
        )

    @property
    def definition(
        self,
    ) -> str | None:

        sense = self.preferred_sense

        if sense is None:
            return None

        return sense.definition

    @property
    def glossary(
        self,
    ) -> str | None:

        sense = self.preferred_sense

        if sense is None:
            return None

        return sense.gloss

    # ---------------------------------------------------------
    # Resolution State
    # ---------------------------------------------------------

    @property
    def resolved(
        self,
    ) -> bool:

        return (
            self.succeeded
            and self.has_entry
            and self.has_sense
        )

    @property
    def unresolved(
        self,
    ) -> bool:

        return not self.resolved

    @property
    def is_unique(
        self,
    ) -> bool:

        return (
            self.candidate_count == 1
        )

    @property
    def is_ambiguous(
        self,
    ) -> bool:

        return self.ambiguity_detected

    @property
    def is_confident(
        self,
    ) -> bool:

        return self.confidence >= 0.80

    # ---------------------------------------------------------
    # Display
    # ---------------------------------------------------------

    @property
    def display_name(
        self,
    ) -> str:

        return "Lexical Resolution Result"

    @property
    def display_text(
        self,
    ) -> str:

        if self.unresolved:
            return "No lexical resolution"

        headword = self.headword or ""

        definition = self.definition or ""

        return (
            f"{headword} → {definition}"
        )

    @property
    def display_description(
        self,
    ) -> str:

        if self.unresolved:
            return "Lexical resolution failed."

        source = self.canonical_source

        if source is None:
            return self.display_text

        return (
            f"{self.display_text} "
            f"[{source.identifier}]"
        )

    # ---------------------------------------------------------

    def __str__(
        self,
    ) -> str:

        return self.display_text
